### ISSUE TITLE
Flatland stopped working

### ISSUE THREAD

**Issue by callumlocke** [thinkpixellab/flatland#121]
I opened up ST3 today and the Flatland theme wasn't working. I tried uninstalling it and reinstalling it (restarting ST3 after each step) but it's still not working.

I am able to use the Flatland Dark and Flatland Monokai syntax highlighting, but the rest of the UI (tabs etc) is not Flatland. I'm just seeing the default ST3 tabs.

What could have caused this? I haven't changed/installed anything, it just stopped working.

**Comment by joelfillmore** [comment]
There was a typo in a recent change, try updating the package again. You might also need to restart Sublime after updating. Let us know if you are still having problems.

**Comment by callumlocke** [comment]
Just tried again, no luck. I fully uninstalled it, restarted sublime, installed it, restarted sublime again. Didn't work.

**Comment by joelfillmore** [comment]
Are you on the latest build: 3065?

**Comment by tdenholm** [comment]
I'm on build 3066 and am experiencing exactly the same issue (even after updating Flatland via Package Control).

**Comment by joelfillmore** [comment]
Strange, I updated to the dev build (3066) and its still working for me. Can you check your Sublime User Settings file? Previously some people have gotten into a bad state where Sublime had put Flatland into the "ignored_packages" list.

**Comment by tdenholm** [comment]
I checked my User Settings file as suggested but my "ignored_packages" list was empty; I also checked my Package Control settings file and that looked OK too. Following that, I then reinstalled Sublime Text completely, and then reinstalled each of my plugins using Package Control... and now it's working. Strange indeed.

**Comment by joelfillmore** [comment]
Cool, glad that fixed it.

**Comment by georgecrawford** [comment]
I had the same thing with 3065. I found that my Preferences.sublime-settings file had reverted to `"theme": "Default.sublime-theme",` for some reason. Updating it to `"theme": "Flatland Dark.sublime-theme",` restored Flatland in the sidebar as expected.
