### ISSUE TITLE
Draw_Active Color

### ISSUE THREAD

**Issue by emage** [thinkpixellab/flatland#124]
How can I change or edit to show the active indented container or element?
Read alot about it but I cannot seem to fine the .tmTheme file in ST3

i want to do this: 
http://wesbos.com/sublime-text-indentation-guide-lines/

thanks

**Comment by aapis** [comment]
`"indent_guide_options": ["draw_active"]` is the setting, which can be styled using the following strings in your .tmTheme file:

```xml
<key>guide</key>
  <string>#3b5364</string>
<key>activeGuide</key>
  <string>#ffc600</string>
<key>stackGuide</key>
  <string>#2aa198</string>
```

**Comment by emage** [comment]
@aapis I can't seem to locate that file to open.  I installed using ST3 package control. Can you point me to the location ?  thanks!

**Comment by aapis** [comment]
The file's name and location depends on your settings.  Find `"color_scheme"` in your user settings, mine is `"Packages/Theme - Aapis.Flatland/Flatland Solarized (Dark).tmTheme"`.  The full path to that folder depends on your OS.  You can see where I added those lines [here](https://github.com/aapis/flatland/blob/master/Flatland%20Solarized%20(Dark).tmTheme#L24).

Not really sure what you mean by "that file" so just in case, your settings can be found under Preferences > Settings - User.

**Comment by emage** [comment]
@aapis  thanks! Got it working
