### ISSUE TITLE
comment color

### ISSUE THREAD

**Issue by kofifus** [thinkpixellab/flatland#128]
Hi, I'm using Flatland Dark in sublime and it's the best except comments (gray) are too weak and hard to read.

Can someone help me with instructions on how to go around changing comment colors ?

Thx!

**Comment by aapis** [comment]
In the Comment field, modify the `foreground` value in `Flatland Dark.tmTheme`.

https://github.com/thinkpixellab/flatland/blob/master/Flatland%20Dark.tmTheme#L58

You can also add a background colour to those strings as well, note the background key/string value.
```xml
<dict>
	<key>name</key>
	<string>Comment</string>
	<key>scope</key>
	<string>comment</string>
	<key>settings</key>
	<dict>
		<key>background</key>
		<string>#ff0000</string>
		<key>fontStyle</key>
		<string></string>
		<key>foreground</key>
		<string>#586E75</string>
	</dict>
</dict>
```

**Comment by kofifus** [comment]
great .. thx!

**Comment by aapis** [comment]
:+1:  

Please close this if your issue is resolved, thanks!
