### ISSUE TITLE
Sublime Text crash

### ISSUE THREAD

**Issue by mcraz** [thinkpixellab/flatland#90]
The theme caught my eye right from the moment I saw it. I installed it and it did actually speed up my dev. 
But, then suddenly one morning when I switch my PC on and my ST3 opened, all was black like odd colors. 
I commented out flatland and default theme was back. Then again I applied back Flatland and all was good until this morning when it decided to stop working completely.

Any idea why ?

![image](https://f.cloud.github.com/assets/4710454/1875884/ec84697e-7902-11e3-918e-e28168eb155c.png)

**Comment by soumenms2015** [comment]
Hello I have similar issue, But I am not able to understand how the above code is added into which file

**Comment by aapis** [comment]
The code referenced by @grayghostvisuals?  You'd add that to the user settings file.  On OSX it's under Sublime Text > Preferences > Settings - User.  On Windows I think it's a top level menu, so just Preferences > Settings - User.
